### ISSUE TITLE
u - matriix表示 by plotly

### ISSUE THREAD

**Issue by TetraMiyazaki** [hirowatari-s/ExploreSearchSystem#19]
がんばる

**Comment by TetraMiyazaki** [comment]
![image](https://user-images.githubusercontent.com/12492226/133685233-1c5ff32a-bdef-4061-99f2-952c417a1af5.png)
これとだいたい同じのが作れたおわり

**Comment by TetraMiyazaki** [comment]
![image](https://user-images.githubusercontent.com/12492226/133685361-f1395e99-3d45-4a3a-9a92-ccd01f0588ca.png)

**Comment by TetraMiyazaki** [comment]
同じですね．
Matplotlibはx = x, y = -y　として表示されるが，Plotlyは x=x, y=yで出力してくれている．（上限反転してるだけ）

**Comment by tanacchi** [comment]
main に取り込んだので Close します．
